hirpc:
  registry:
    address: 127.0.0.1:2181
  protocol:
    name: hirpc
    host: 127.0.0.1
    port: 8081
    serialization: protobuf
    protobufScanBasePackages: com.hirpc,tutorial
    heartbeatTime: 60000
  application:
    version: 1.0
    name: demo

server:
  port: 8082
logging:
  config: classpath:log4j2.xml
